//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace twclient.Resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("twclient.Resource.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Fav / {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Contents_Button_Fav {
            get {
                return ResourceManager.GetString("String_Contents_Button_Fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Contents_Button_Reply {
            get {
                return ResourceManager.GetString("String_Contents_Button_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet / {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Contents_Button_Retweet {
            get {
                return ResourceManager.GetString("String_Contents_Button_Retweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnFav / {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Contents_Button_UnFav {
            get {
                return ResourceManager.GetString("String_Contents_Button_UnFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnRetweet / {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Contents_Button_UnRetweet {
            get {
                return ResourceManager.GetString("String_Contents_Button_UnRetweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favoriteを取り消ししますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_CancelFavoriteMessage {
            get {
                return ResourceManager.GetString("String_FormTimeLine_CancelFavoriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel Favorite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_CancelFavoriteTitle {
            get {
                return ResourceManager.GetString("String_FormTimeLine_CancelFavoriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweetを取り消ししますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_CancelRetweetMessage {
            get {
                return ResourceManager.GetString("String_FormTimeLine_CancelRetweetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel Retweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_CancelRetweetTitle {
            get {
                return ResourceManager.GetString("String_FormTimeLine_CancelRetweetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweetを削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_DeleteTweetMessage {
            get {
                return ResourceManager.GetString("String_FormTimeLine_DeleteTweetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_DeleteTweetTitle {
            get {
                return ResourceManager.GetString("String_FormTimeLine_DeleteTweetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favoriteしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_FavoriteMessage {
            get {
                return ResourceManager.GetString("String_FormTimeLine_FavoriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_FavoriteTitle {
            get {
                return ResourceManager.GetString("String_FormTimeLine_FavoriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_Minitus {
            get {
                return ResourceManager.GetString("String_FormTimeLine_Minitus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引用Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_Quote {
            get {
                return ResourceManager.GetString("String_FormTimeLine_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返信(@{0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_Reply {
            get {
                return ResourceManager.GetString("String_FormTimeLine_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RT by {0} (@{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_RetweetBy {
            get {
                return ResourceManager.GetString("String_FormTimeLine_RetweetBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweetしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_RetweetMessage {
            get {
                return ResourceManager.GetString("String_FormTimeLine_RetweetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_RetweetTitle {
            get {
                return ResourceManager.GetString("String_FormTimeLine_RetweetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_SearchWord_OR {
            get {
                return ResourceManager.GetString("String_FormTimeLine_SearchWord_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_Seconds {
            get {
                return ResourceManager.GetString("String_FormTimeLine_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_TimelineName_HOME {
            get {
                return ResourceManager.GetString("String_FormTimeLine_TimelineName_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LIKE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_TimelineName_LIKE {
            get {
                return ResourceManager.GetString("String_FormTimeLine_TimelineName_LIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LISTS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_TimelineName_LISTS {
            get {
                return ResourceManager.GetString("String_FormTimeLine_TimelineName_LISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MENTION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_TimelineName_MENTION {
            get {
                return ResourceManager.GetString("String_FormTimeLine_TimelineName_MENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SEARCH に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_TimelineName_SEARCH {
            get {
                return ResourceManager.GetString("String_FormTimeLine_TimelineName_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FormTimeLine_TimelineName_USER {
            get {
                return ResourceManager.GetString("String_FormTimeLine_TimelineName_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consumer Key,Secretの設定がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Twitter_Consumer_Error {
            get {
                return ResourceManager.GetString("String_Twitter_Consumer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部エラー（Timeline取得） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Twitter_InternalError1 {
            get {
                return ResourceManager.GetString("String_Twitter_InternalError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前解決ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Twitter_NameResolutionFailure {
            get {
                return ResourceManager.GetString("String_Twitter_NameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Twitter_NotFoundUser {
            get {
                return ResourceManager.GetString("String_Twitter_NotFoundUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Twitter_NoUpdate {
            get {
                return ResourceManager.GetString("String_Twitter_NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Twitter_SendError {
            get {
                return ResourceManager.GetString("String_Twitter_SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   応答が一定時間ありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Twitter_Timeout {
            get {
                return ResourceManager.GetString("String_Twitter_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Twitter_Updating {
            get {
                return ResourceManager.GetString("String_Twitter_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   待機中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Twitter_Waiting {
            get {
                return ResourceManager.GetString("String_Twitter_Waiting", resourceCulture);
            }
        }
    }
}
